### ISSUE TITLE
create one pager website for probr

### ISSUE THREAD

**Issue by gmazlami** [probr/probr-analysis#11]
set up a website for Probr (like github pages)

possibly in german and english

**Comment by joe4dev** [comment]
- Impressum
- Short description of core and analysis
- List features
- Screenshots of analysis views
- ev. slideshow

**Comment by dschoeni** [comment]
Check: https://github.com/probr/probr.github.io

To add/change content:
- Pull Repository
- Checkout Development Branch
- npm install & bower install
- Use grunt serve to debug & change stuff
- Use `grunt buildcontrol:github` to deploy.
- Do not manually merge into master.

Same steps are also written in the README of the Repository.

**Comment by gmazlami** [comment]
Consider this closed, issues concerning the web-site should be opened in the probr.github.io repository
