### ISSUE TITLE
conceptualize and implement sessions

### ISSUE THREAD

**Issue by dschoeni** [probr/probr-analysis#14]
Write a MapReduce Query that identifies sessions from packets, which are minimum 5 minutes long. A sessions should contain a start and end date, as well as the identifying MAC-Address of the device. This should be an incremental MapReduce Task.

`{ mac_address: XX-YY-XX, start: IsoDate(), end: IsoDate() }`

**Comment by gmazlami** [comment]
Has been implemented.
