### ISSUE TITLE
archive old data in mongodb

### ISSUE THREAD

**Issue by dschoeni** [probr/probr-analysis#16]
To reduce the workload of our tasks and make it easier to drive complex analysis tasks, we should define:
- a timeframe that is usable to work (f.E. 1 week)
- setup a cron that automatically archives & encrypts the data older than the defined timeframe

**Comment by sebastian-stephan** [comment]
👍

**Comment by dschoeni** [comment]
It's actually pretty simple. Let's discuss it today what the timeframe should be. MongoDB already has a TTL-Field to accomodate such use cases (http://docs.mongodb.org/manual/tutorial/expire-data/).

**Comment by dschoeni** [comment]
Has been implemented, but will not be used yet.
