### ISSUE TITLE
redesign/concept for probr analysis

### ISSUE THREAD

**Issue by dcale** [probr/probr-analysis#29]
- ~~merge session and loyalty, rename to utilization~~ done
- global filter for tags and daterange
- heatmap becomes "location" -> either you filter via tags/daterange or mac address
- ~~devices beomces "stats" -> shorten the last day seen to 50 devices and xxx more~~ done
- ~~packets becomes "log"~~ done

**Comment by dschoeni** [comment]
See our wonderful sketches:

![img_20151122_161957](https://cloud.githubusercontent.com/assets/1913623/11324544/1c3576bc-9135-11e5-8cab-a47b2f4cc573.jpg)
![img_20151122_162003](https://cloud.githubusercontent.com/assets/1913623/11324548/1d834e90-9135-11e5-891d-c2288f9bf002.jpg)

**Comment by gmazlami** [comment]
Renaming is done completely. URL parameters for all "use case"-views are done too.
