### ISSUE TITLE
Locations should have tags

### ISSUE THREAD

**Issue by gmazlami** [probr/probr-analysis#31]
Include all the tags of the packets used to compute the location into the location object.

**Comment by sebastian-stephan** [comment]
Seems not wo work (local and remote). Ain't no tags there. :smirk_cat: 

Also wouldn't [this](https://github.com/probr/probr-analysis/blob/dev/worker/components/location/location.mapreduce.js#L69) produce double entries? We should aim for a set like list of tags like [here](https://github.com/probr/probr-analysis/blob/feature/newSessions/worker/components/session/session.mapreduce.js#L40-L44)
