### ISSUE TITLE
probr-core generating pcaps, but probr-analysis "No Packets received yet." i.e. no data

### ISSUE THREAD

**Issue by rrodstein** [probr/probr-analysis#59]
Thank you in advance for your support!

I've successfully stud-up core, and analysis using the docker instructions from probr.ch, and the tips from issues #22, and #58. Core is receiving pcaps from a probe, but the analysis GUI is empty, i.e. no data, and from the /live page we see "No Packets received yet.". We get the same results, i.e. collecting pcaps in core, but no data in  analysis on ubuntu 14.04, 16.04, and 17.04 with the docker, and python installations.

Could you please assist with tips to troubleshoot the analysis GUI without data even when core is accepting pcaps?

Respectfully,

FYI, 
/probr/probr-analysis$ sudo docker ps
[sudo] password for: 
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                                            NAMES
a076b1f532e2        probr/core-analysis-nginx:latest   "/usr/sbin/nginx"        About an hour ago   Up About an hour    0.0.0.0:80->80/tcp                               probrcore_nginx_1
8a4135cf5409        probr/analysis:latest              "node dist/server/ap…"   About an hour ago   Up About an hour    0.0.0.0:8080->8080/tcp                           probranalysis_analysis_1
b7f9c6998b01        probr/analysis:latest              "node dist/worker/ap…"   About an hour ago   Up About an hour                                                     probranalysis_analysis_worker_1
9e3b1f08ce50        probr/core:latest                  "sh install/docker/w…"   About an hour ago   Up About an hour    0.0.0.0:8001->8001/tcp                           probrcore_web_1
d0e909122c36        probr/core:latest                  "sh install/docker/w…"   About an hour ago   Up About an hour                                                     probrcore_worker_1
7cdf189332d2        mongo:3.0.6                        "/entrypoint.sh mong…"   About an hour ago   Up About an hour    27017/tcp                                        probrcore_mongodb_1
abab802518c2        tutum/influxdb:0.9                 "/run.sh"                About an hour ago   Up About an hour    0.0.0.0:8083->8083/tcp, 0.0.0.0:8086->8086/tcp   probrcore_influxdb_1
022bad945c84        postgres:9.4.5                     "/docker-entrypoint.…"   About an hour ago   Up About an hour    5432/tcp                                         probrcore_postgres_1
3666ad39a57f        probr/core:latest                  "sh install/docker/w…"   About an hour ago   Up About an hour    0.0.0.0:8002->8002/tcp                           probrcore_websocket_1
67d28b14452d        redis:2.8.19                       "/entrypoint.sh redi…"   About an hour ago   Up About an hour    6379/tcp

**Comment by rrodstein** [comment]
Hi,

I've got both core and analysis working using docker on ubuntu17.04, 16.04, and 14.04. Please edit the core "docker-compose-analysis.yml" file and add the bottom two lines (from "external_links") to get packets into the analysis page:

# probr-core, websockets
worker:
   image: probr/core:latest
   command: sh install/docker/web/worker.sh
   volumes_from:
     - dataprobr
   links:
     - postgres:postgres
     - redis:redis
   external_links:
     - probrcore_mongodb_1:mongodb

To get it all working:
1st step: probr-core$ sudo docker-compose up -d
2nd step: probr-analysis$ sudo docker-compose up -d
3rd step with above edit: probr-core$ sudo docker-compose -f docker-compose-analysis.yml up -d
And your good to go!

Please let me know if you need any further details.

Have any of you figured out how to load a floor plan, i.e. rooms, or get google maps to work in the location/heatmap page?

Respectfully,

**Comment by KhurramPirov** [comment]
> Hi,
> 
> I've got both core and analysis working using docker on ubuntu17.04, 16.04, and 14.04. Please edit the core "docker-compose-analysis.yml" file and add the bottom two lines (from "external_links") to get packets into the analysis page:
> 
> # probr-core, websockets
> worker:
> image: probr/core:latest
> command: sh install/docker/web/worker.sh
> volumes_from:
> - dataprobr
> links:
> - postgres:postgres
> - redis:redis
> external_links:
> - probrcore_mongodb_1:mongodb
> 
> To get it all working:
> 1st step: probr-core$ sudo docker-compose up -d
> 2nd step: probr-analysis$ sudo docker-compose up -d
> 3rd step with above edit: probr-core$ sudo docker-compose -f docker-compose-analysis.yml up -d
> And your good to go!
> 
> Please let me know if you need any further details.
> 
> Have any of you figured out how to load a floor plan, i.e. rooms, or get google maps to work in the location/heatmap page?
> 
> Respectfully,

Hi, thank you for your guide but I still cant send all collected data from media/captures to any db. I added two lines in external links of docker-compose-analysis.yml but still have no any packets in probr analysis.
