### ISSUE TITLE
improve heatmap

### ISSUE THREAD

**Issue by dschoeni** [probr/probr-analysis#6]
So, what we have now with the utilization-collection is a log of visits in the following format:

``` javascript{
_id: Date,
value: {
      mac_address_src: String,
      totalSignalStrength: Number,
      location: GeoJSONPoint,
   }
}
```

So we know when a certain probe-request has been picked up from all devices, and to what device it belonged. We also have a triangulated position of the device, although the accuracy of this information needs to be validated.

Also, the Map-View is able to display 30-minutes extract in form of a heat-map. 

What still needs to be done:
- heatmap per device: each device should have its own color in the heatmap. Those that occur often should be easily distinguishable.
- have a slider to easily slide through the day, respectively change the 30min segments that get queried from the backend.

**Comment by gmazlami** [comment]
Does the first idea (color per device) make sense?

A heatmap should change color based on the number of entitties/density

e.g. high density --> red
low density --> blue

**Comment by gmazlami** [comment]
Maybe expand the radius of the heatmap clouds, and play around with the colors, so it looks better
